### PR TITLE
Make package modular

### LINKED ISSUE #7: __init__.py should contains initiators
I think your code need modular approach. It's bad practice to add all code in one. 

## let me show you my project:

**Creating Python Package using Jupyter Notebook.**

- [GitHub](https://github.com/kingabzpro/Creating-Python-Package-using-Jupyter-Notebook)
- [Deepnote Project](https://deepnote.com/project/Creating-Python-Package-in-Jupyter-Notebook-JvApLhCiQIqj-0yR-PAfdQ/%2Fpython_packages.ipynb)
- [Deepnote Notebook](https://deepnote.com/@abid/Creating-Python-Package-in-Jupyter-Notebook-JvApLhCiQIqj-0yR-PAfdQ)
- [Analytics Vidhya](https://www.analyticsvidhya.com/blog/2021/07/creating-data-science-python-package-using-jupyter-notebook/)
﻿

### PR DESCRIPTION
**Pull request by martinm07**
Improve formatting of pip package according to #7 (i.e. utilize modular programming).

### CODE REVIEW

**Comment by kingabzpro** [comment]
Don't add examples into doc strings. I think rest of it is good. Did you test your code?

**Comment by martinm07** [comment]
Really? I thought having examples was normal... But I'll trust you.
And yes, I've tested the distribution locally, so it should be good to go.

**Comment by martinm07** [comment]
Is this good?

**Comment by kingabzpro** [comment]
Good to go. Try adding tags in github. You can auto mate your work with github actions
which will upload to pip and create tag

**Pull request merged**
